# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

# This workflow executes a single test, optionally gathering code coverage and logs.

name: Create Or Update issue

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string
      labels:
        required: false
        type: string

permissions:
  issues: write # Required to create issues.

jobs:
  create_or_update_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          TITLE: ${{inputs.title}}
          BODY: ${{inputs.body}}
          LABELS: ${{inputs.labels}}

        with:
          script: |
            const owner = process.env.GITHUB_REPOSITORY.split('/')[0]
            const repo = process.env.GITHUB_REPOSITORY.split('/')[1]
            const body = process.env.BODY;
            const title = process.env.TITLE;
            const labels = process.env.LABELS;
            const label_array = labels ? labels.split(',') : [];
            console.log(`Creating issue ${title}`);
            console.log(context);

            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              state: 'open',
              title: title,
            });


            const issues = await github.paginate(opts);

            console.log(issues);
            if (issues.length > 0) {
              const issue = issues[0];
              await github.rest.issues.update({
                owner: owner,
                repo: repo,
                issue_number: issue.number,
                body: body,
                labels: label_array,
              });
            } else {
              await github.rest.issues.create({
                owner: owner,
                repo: repo,
                title: title,
                body: body,
                labels: label_array,
              });
            }
