# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Kernel_Test

# Run this work flow when the "MSBuild workflow completes"
on:
  workflow_run:
    workflows: ["MSBuild"]
    types:
      - completed

jobs:
  test:
    strategy:
      matrix:
        configurations: [Debug, Release]

    runs-on: [windows, self-hosted]
    steps:
    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v2.14.1
      with:
        workflow: build.yml
        workflow_conclusion: success
        commit: ${{ github.event.workflow_run.head_commit.id }}
        name: Build x64 ${{ matrix.configurations }}
        path: ${{ github.workspace }}

    - name: Install eBPF
      working-directory: ${{ github.workspace }}
      run: ./install-ebpf.bat

    - name: Run kernel driver tests
      working-directory: ${{ github.workspace }}
      run: ./run_tests.bat /noinstall

    - name: Uninstall eBPF
      working-directory: ${{ github.workspace }}
      run: ./uninstall-ebpf.bat
