# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

# This workflow updates NuGet packages and creates a pull request with the changes.
name: nuget_update

on:
  # Allow this workflow to be manually triggered.
  workflow_dispatch:

  # Run this once a week on saturday at 9pm UTC.
  schedule:
    - cron: '0 21 * * 6'

permissions:
    contents: read

jobs:
  update:
    runs-on: windows-2022

    steps:
    # Check out the main repo.
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        # Only check out main repo, not submodules.
        ref: ${{ github.event.workflow_run.head_branch }}

    # Update nuget packages used by the solution.
    - name: Update NuGet packages
      run: |
        nuget update -noninteractive -verbosity quiet ebpf-for-windows.sln

    # Check if there are any changes.
    - name: Check for changes
      id: check
      run: |
        if git diff --quiet; then
          echo "::set-output name=changes::false"
        else
          echo "::set-output name=changes::true"
        fi

    # Commit changes if any.
    - name: Commit changes
      if: steps.check.outputs.changes == 'true'
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -s -m "Update NuGet packages" -m "This is an automated commit by the GitHub Action 'nuget_update'."
        git push


    - name: Create Pull Request
      if: steps.check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update NuGet packages
        title: Update NuGet packages
        body: |
          This is an automated pull request by the GitHub Action 'nuget_update'.
          Please review the changes and merge if appropriate.
        labels: |
          automated pr
          nuget update
