# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

on:
  pull_request:

jobs:
  build:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run code-spell-checker
        uses: betrybe/code-spell-checker-action@main
        with:
          files: '**/*'
          token: ${{ secrets.GITHUB_TOKEN }}